#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Hoho.Android.UsbSerial.Examples.Resource", IsApplication=true)]

namespace Hoho.Android.UsbSerial.Examples
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7F010000
			public const int enter_bottom = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int enter_left = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int enter_right = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int enter_top = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int exit_bottom = 2130771972;
			
			// aapt resource value: 0x7F010005
			public const int exit_left = 2130771973;
			
			// aapt resource value: 0x7F010006
			public const int exit_right = 2130771974;
			
			// aapt resource value: 0x7F010007
			public const int exit_top = 2130771975;
			
			// aapt resource value: 0x7F010008
			public const int fade_in = 2130771976;
			
			// aapt resource value: 0x7F010009
			public const int fade_out = 2130771977;
			
			// aapt resource value: 0x7F01000A
			public const int flip_in = 2130771978;
			
			// aapt resource value: 0x7F01000B
			public const int flip_out = 2130771979;
			
			// aapt resource value: 0x7F01000C
			public const int scale_in = 2130771980;
			
			// aapt resource value: 0x7F01000D
			public const int scale_out = 2130771981;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7F020000
			public const int alignContent = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int alignItems = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int dividerDrawable = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int dividerDrawableHorizontal = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int dividerDrawableVertical = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int flexDirection = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int flexWrap = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int justifyContent = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int layoutManager = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int layout_alignSelf = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int layout_flexBasisPercent = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int layout_flexGrow = 2130837515;
			
			// aapt resource value: 0x7F02000C
			public const int layout_flexShrink = 2130837516;
			
			// aapt resource value: 0x7F02000D
			public const int layout_maxHeight = 2130837517;
			
			// aapt resource value: 0x7F02000E
			public const int layout_maxWidth = 2130837518;
			
			// aapt resource value: 0x7F02000F
			public const int layout_minHeight = 2130837519;
			
			// aapt resource value: 0x7F020010
			public const int layout_minWidth = 2130837520;
			
			// aapt resource value: 0x7F020011
			public const int layout_order = 2130837521;
			
			// aapt resource value: 0x7F020012
			public const int layout_wrapBefore = 2130837522;
			
			// aapt resource value: 0x7F020013
			public const int reverseLayout = 2130837523;
			
			// aapt resource value: 0x7F020014
			public const int showDivider = 2130837524;
			
			// aapt resource value: 0x7F020015
			public const int showDividerHorizontal = 2130837525;
			
			// aapt resource value: 0x7F020016
			public const int showDividerVertical = 2130837526;
			
			// aapt resource value: 0x7F020017
			public const int spanCount = 2130837527;
			
			// aapt resource value: 0x7F020018
			public const int stackFromEnd = 2130837528;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7F030000
			public const int item_touch_helper_max_drag_scroll_per_frame = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int item_touch_helper_swipe_escape_max_velocity = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int item_touch_helper_swipe_escape_velocity = 2130903042;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F040000
			public const int icon = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int logo_dfr = 2130968577;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F050000
			public const int auto = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int baseline = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int beginning = 2131034114;
			
			// aapt resource value: 0x7F050003
			public const int center = 2131034115;
			
			// aapt resource value: 0x7F050004
			public const int column = 2131034116;
			
			// aapt resource value: 0x7F050005
			public const int column_reverse = 2131034117;
			
			// aapt resource value: 0x7F050006
			public const int end = 2131034118;
			
			// aapt resource value: 0x7F050007
			public const int flex_end = 2131034119;
			
			// aapt resource value: 0x7F050008
			public const int flex_start = 2131034120;
			
			// aapt resource value: 0x7F050009
			public const int imageButton1 = 2131034121;
			
			// aapt resource value: 0x7F05000A
			public const int item_touch_helper_previous_elevation = 2131034122;
			
			// aapt resource value: 0x7F05000B
			public const int middle = 2131034123;
			
			// aapt resource value: 0x7F05000C
			public const int none = 2131034124;
			
			// aapt resource value: 0x7F05000D
			public const int nowrap = 2131034125;
			
			// aapt resource value: 0x7F05000E
			public const int row = 2131034126;
			
			// aapt resource value: 0x7F05000F
			public const int row_reverse = 2131034127;
			
			// aapt resource value: 0x7F050010
			public const int space_around = 2131034128;
			
			// aapt resource value: 0x7F050011
			public const int space_between = 2131034129;
			
			// aapt resource value: 0x7F050012
			public const int stretch = 2131034130;
			
			// aapt resource value: 0x7F050013
			public const int webView1 = 2131034131;
			
			// aapt resource value: 0x7F050014
			public const int wrap = 2131034132;
			
			// aapt resource value: 0x7F050015
			public const int wrap_reverse = 2131034133;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F060000
			public const int UsbHost = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int UsbWebView = 2131099649;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7F070000
			public const int beep = 2131165184;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F080000
			public const int app_name = 2131230720;
			
			// aapt resource value: 0x7F080001
			public const int refreshing = 2131230721;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			// aapt resource value: { 0x7F020000,0x7F020001,0x7F020002,0x7F020003,0x7F020004,0x7F020005,0x7F020006,0x7F020007,0x7F020014,0x7F020015,0x7F020016 }
			public static int[] FlexboxLayout = new int[] {
					2130837504,
					2130837505,
					2130837506,
					2130837507,
					2130837508,
					2130837509,
					2130837510,
					2130837511,
					2130837524,
					2130837525,
					2130837526};
			
			// aapt resource value: 0
			public const int FlexboxLayout_alignContent = 0;
			
			// aapt resource value: 1
			public const int FlexboxLayout_alignItems = 1;
			
			// aapt resource value: 2
			public const int FlexboxLayout_dividerDrawable = 2;
			
			// aapt resource value: 3
			public const int FlexboxLayout_dividerDrawableHorizontal = 3;
			
			// aapt resource value: 4
			public const int FlexboxLayout_dividerDrawableVertical = 4;
			
			// aapt resource value: 5
			public const int FlexboxLayout_flexDirection = 5;
			
			// aapt resource value: 6
			public const int FlexboxLayout_flexWrap = 6;
			
			// aapt resource value: 7
			public const int FlexboxLayout_justifyContent = 7;
			
			// aapt resource value: { 0x7F020009,0x7F02000A,0x7F02000B,0x7F02000C,0x7F02000D,0x7F02000E,0x7F02000F,0x7F020010,0x7F020011,0x7F020012 }
			public static int[] FlexboxLayout_Layout = new int[] {
					2130837513,
					2130837514,
					2130837515,
					2130837516,
					2130837517,
					2130837518,
					2130837519,
					2130837520,
					2130837521,
					2130837522};
			
			// aapt resource value: 0
			public const int FlexboxLayout_Layout_layout_alignSelf = 0;
			
			// aapt resource value: 1
			public const int FlexboxLayout_Layout_layout_flexBasisPercent = 1;
			
			// aapt resource value: 2
			public const int FlexboxLayout_Layout_layout_flexGrow = 2;
			
			// aapt resource value: 3
			public const int FlexboxLayout_Layout_layout_flexShrink = 3;
			
			// aapt resource value: 4
			public const int FlexboxLayout_Layout_layout_maxHeight = 4;
			
			// aapt resource value: 5
			public const int FlexboxLayout_Layout_layout_maxWidth = 5;
			
			// aapt resource value: 6
			public const int FlexboxLayout_Layout_layout_minHeight = 6;
			
			// aapt resource value: 7
			public const int FlexboxLayout_Layout_layout_minWidth = 7;
			
			// aapt resource value: 8
			public const int FlexboxLayout_Layout_layout_order = 8;
			
			// aapt resource value: 9
			public const int FlexboxLayout_Layout_layout_wrapBefore = 9;
			
			// aapt resource value: 8
			public const int FlexboxLayout_showDivider = 8;
			
			// aapt resource value: 9
			public const int FlexboxLayout_showDividerHorizontal = 9;
			
			// aapt resource value: 10
			public const int FlexboxLayout_showDividerVertical = 10;
			
			// aapt resource value: { 0x10100C4,0x10100F1,0x7F020008,0x7F020013,0x7F020017,0x7F020018 }
			public static int[] RecyclerView = new int[] {
					16842948,
					16842993,
					2130837512,
					2130837523,
					2130837527,
					2130837528};
			
			// aapt resource value: 1
			public const int RecyclerView_android_descendantFocusability = 1;
			
			// aapt resource value: 0
			public const int RecyclerView_android_orientation = 0;
			
			// aapt resource value: 2
			public const int RecyclerView_layoutManager = 2;
			
			// aapt resource value: 3
			public const int RecyclerView_reverseLayout = 3;
			
			// aapt resource value: 4
			public const int RecyclerView_spanCount = 4;
			
			// aapt resource value: 5
			public const int RecyclerView_stackFromEnd = 5;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7F0A0000
			public const int device_filter = 2131361792;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
